version: '2'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka-manager:  
    image: sheepkiller/kafka-manager
    environment:
        ZK_HOSTS: zoo1:2181
    ports:
      - "9000:9000"
    links:
      - zoo1
  # kafka version: 1.1.0
  # scala version: 2.12
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.225.10.115
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
      - zoo1
    container_name: kafka
  kafka2:
    image: wurstmeister/kafka
    ports:
    - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.225.10.115
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
    - zoo1
    container_name: kafka
  kafka3:
    image: wurstmeister/kafka
    ports:
    - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.225.10.115
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
    - zoo1
    container_name: kafka